### ISSUE TITLE
"Failed to recive response" when using sort clips by "Views" with 100 clips limit

### ISSUE THREAD

**Issue by ftk789** [JamesYL/TwitchClips#2]

**Comment by ftk789** [comment]
I guess the clip limiter doesn't work

**Comment by JamesYL** [comment]
@ftk789 Hey I'm unaware of the error? How do I recreate it?

**Comment by ftk789** [comment]
choose a channel and setup the login token, and then put it as "views" and limit the clips to 100

**Comment by JamesYL** [comment]
What you're describing isn't related to this repo... there is no login token?

**Comment by ftk789** [comment]
NVM i opened an issue in the wrong repository, i am sorry LUL
